---
version: 2.1

orbs:
  executor-tools: twdps/executor-tools@4.0.1
  op: twdps/onepassword@3.0.0
  do: twdps/pipeline-events@5.0.1

globals:
  - &context platform
  - &shell op run --env-file op.env -- /bin/bash -eo pipefail

on-push-main: &on-each-run
  branches:
    only: /main/
  tags:
    only: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /.*/

commands:

  set-environment:
    steps:
      - op/env
      - op/write-to-file:
          op-value: platform/svc-cosign-private-key/notesPlain
          out-file: cosign.key
      - op/write-to-file:
          op-value: platform/svc-cosign-public-key/notesPlain
          out-file: cosign.pub

workflows:

  build and publish:
    jobs:
      - executor-tools/dev-release:
          name: image build
          context: *context
          shell: *shell
          image: twdps/circleci-python-builder
          tag: edge
          snyk-scan: true
          snyk-severity-threshold: high
          snyk-organization: twplatformlabs
          bats-test: true
          bats-run-container-name: circleci-python-builder-edge
          bats-entry-point: /bin/ash
          bats-test-path: test/circleci_python_builder.bats
          opencontainer-labels: true
          security-scan-nofail: true
          after-checkout:
            - op/env
          filters: *on-each-run

      - executor-tools/publish:
          name: release
          context: *context
          shell: *shell
          image: twdps/circleci-python-builder
          pull-tag: edge
          release-tag: stable
          sign-image: true
          sbom: true
          after-checkout:
            - set-environment
          requires:
            - image build
          filters: *on-tag-main

      - do/gh-release:
          name: generate release notes
          shell: *shell
          context: *context
          notes-from-file: release.md
          include-commit-msg: true
          upload-artifacts: true
          artifact-folder: workspace
          before-release:
            - set-environment
          requires:
            - release
          filters: *on-tag-main

  schedule ci build:
    jobs:
      - do/schedule-pipeline:
          name: configure weekly trigger
          context: *context
          scheduled-pipeline-name: weekly-ci-build
          scheduled-pipeline-description: |
            Automatically trigger image build on a weekly schedule. Failure of
            this recurring build indicates new releases of dependent packages.
          hours-of-day: "[1]"
          days-of-week: "[\"SUN\"]"
          before-schedule:
            - op/env
          filters: *on-tag-main
